---
title: "AY_ClassProject_FramingAI"
author: "AY Kuwornu"
date: "2024-11-12"
output: html_document
---

##AI & Disaster Framing through Organizational Press Releases

#Loading relevant packages and libraries
```{r}
#install.packages("pdftools")
library(tidyverse)
library(pdftools)
library(stringr)
library(tidytext)

```

##Loading articles for study

```{r}
#Using pdftools package. Good for basic PDF extraction
#Nov 16: removed split_file folder in a cleanup
text <- pdf_text("../AYClassProjectRepo/AY_framingAI.PDF")
#pdf_text reads the text from a PDF file.
writeLines(text, "../AYClassProjectRepo/AY_framingAI.txt")
#writeLines writes this text to a text file

## Split text to separate articles on common identifier
# Step 1: Read text file into R
file_path <- "../AYClassProjectRepo/AY_framingAI.txt"
text_data <- readLines(file_path)

# Step 2: Combine lines into one single string
text_combined <- paste(text_data, collapse = "\n")

# Step 3: Split the text by the "End of Document" phrase
documents <- strsplit(text_combined, "End of Document")[[1]]

# Step 4: Write each section to a new file
output_dir <- "../AYClassProjectRepo/extracted files"
for (i in seq_along(documents)) {
  output_file <- file.path(output_dir, paste0("AY_framingAI_", i, ".txt"))
  writeLines(documents[[i]], output_file)
}

cat("Files created:", length(documents), "\n")
```

#New activity here

```{r}


```

#New activity here

```{r}


```

